# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7c7da59adf08a79a7f9620d870466fa623fd242b4a91346b66404a8e95ecd886bc973ea8e5ffcd4d62a00aa7ff79db2ac6db28edcbe6005bb47f02471dc9af4

test:
  secret_key_base: 4b9b07ea3bd4e2137d35c9a185985276e73867d4111299b999556576344df52977c01539fcb5aa0f3b2786d9e165be8c0d64ffb84508e26f08df18ae9e8f08f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
